
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Fri Mar 11 12:21:39 GMT 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int slash = 27;
  public static final int STRING_LITERAL = 48;
  public static final int SQRT = 29;
  public static final int LTE = 35;
  public static final int plus = 24;
  public static final int hat = 28;
  public static final int LOAD = 5;
  public static final int End_Of_File = 7;
  public static final int minus = 25;
  public static final int REPEAT = 19;
  public static final int comma = 16;
  public static final int CHARACTER_LITERAL = 50;
  public static final int AND = 36;
  public static final int NOT = 31;
  public static final int IS = 30;
  public static final int LT = 33;
  public static final int quote = 14;
  public static final int OR = 37;
  public static final int BOOL = 43;
  public static final int UNTIL = 20;
  public static final int NUM = 39;
  public static final int EOL = 8;
  public static final int ASSIGN = 17;
  public static final int IF = 18;
  public static final int COORD = 46;
  public static final int EOF = 0;
  public static final int HEAR = 11;
  public static final int FOREVER = 21;
  public static final int RETURN = 10;
  public static final int TRUE = 44;
  public static final int error = 1;
  public static final int asterix = 26;
  public static final int lparen = 12;
  public static final int START = 2;
  public static final int VOID = 47;
  public static final int coord_lit = 42;
  public static final int GTE = 34;
  public static final int rparen = 13;
  public static final int COLON = 4;
  public static final int ELSE = 22;
  public static final int END = 9;
  public static final int num_lit = 49;
  public static final int STRING = 41;
  public static final int char_lit = 40;
  public static final int AT = 6;
  public static final int FALSE = 45;
  public static final int lambda = 38;
  public static final int GT = 32;
  public static final int SIGNAL = 23;
  public static final int dot = 15;
  public static final int IDENTIFIER = 3;
}

